### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by Draak-sub** [kozuna-1216/learn_github_actions#1]
タイトルのカラーをもう少しオレンジにして

```css
h1 {
  color: #e8d4b2;
}
```
